language: node_js
node_js:
  - "8"
script:
  - "npm test"
  - "npm run build"
after_success: 
  - "./node_modules/.bin/codecov"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: "./dist"
  on:
    branch: master